// STYLE
import "./globals.css";
import { Inter } from "next/font/google";

// COMPONENTS
import Header from "@/components/Header";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IMDb Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {/* HEADER */}
          <Header />
          {/* NAVBAR */}
          {/* SEARCH */}
          {children}{" "}
        </Providers>
      </body>
    </html>
  );
}
